### ISSUE TITLE
couldn't find  "liblanjie.so"

### ISSUE THREAD

**Issue by molyswu** [wlanjie/AndroidFFmpeg#14]
Hi wlanjie!
I compiled the AndroidFFmpeg with
 Andriod studio2.2,Had fowller error:

![8](https://cloud.githubusercontent.com/assets/11438784/21517803/05edb9e4-cd1d-11e6-9fed-f05b60cfd584.png)

**Comment by wlanjie** [comment]
需要先执行tools目录下的compile-x264.sh ./compile-x264.sh all 编译出libx264的静态库,然后就可以了

**Comment by molyswu** [comment]
执行./compile-x264.sh all有如何下：

![5](https://cloud.githubusercontent.com/assets/11438784/21535800/3d00d6bc-cdb5-11e6-9a5c-eb3bf31e7855.png)

**Comment by molyswu** [comment]
在哪里定义

**Comment by wlanjie** [comment]
@molyswu 环境变量里,设置ANDROID_NDK=ndk的path, ANDROID_SDK=sdk的path

**Comment by wlanjie** [comment]
对的

**Comment by molyswu** [comment]
Hi,wlanjie!你可以发extra里的文件：ffmpeg ，opencv,x264给我吗？我在linux Android SDK搞不出来，现在很急用。
跪求！






Thanks
Best and Regards!
 
From: wlanjie
Date: 2016-12-29 14:51
To: wlanjie/AndroidFFmpeg
CC: molyswu; Mention
Subject: Re: [wlanjie/AndroidFFmpeg] couldn't find "liblanjie.so" (#14)
对的

**Comment by wlanjie** [comment]
留个联系方式吧,我联系你

**Comment by molyswu** [comment]
Hi,wlanjie!

我现在用windows Android studio 编译FFmpeg，build apk 有报如下错误：

我的联系：
QQ:339287899 口令（QQQ）
mobile:15218370998
吴士孙




Thanks
Best and Regards!
 
From: wlanjie
Date: 2016-12-31 18:39
To: wlanjie/AndroidFFmpeg
CC: molyswu; Mention
Subject: Re: [wlanjie/AndroidFFmpeg] couldn't find "liblanjie.so" (#14)
留个联系方式吧,我联系你

**Comment by molyswu** [comment]
Hi,wlanjie!

我现在用windows Android studio 编译FFmpeg，build apk 有报如下错误：
![Uploading Ins.png…]()

**Comment by molyswu** [comment]
Hi,wlanjie!

我现在用windows Android studio 编译FFmpeg，build apk 有报如下错误：
![Uploading Ins.png…]()
