### ISSUE TITLE
clone libx264到extra目录,执行 sh tools/compile-x264.sh all 生成libx264.a静态库 导入Streaming到Android 

### ISSUE THREAD

**Issue by fujiangren** [wlanjie/AndroidFFmpeg#17]
clone libx264到extra目录,执行 sh tools/compile-x264.sh all 生成libx264.a静态库 导入Streaming到Android 
这个什么意思啊？能细说 么 谢谢

**Comment by wlanjie** [comment]
这个不需要了,这个库我都编译好放上来了,在tools下有x264-build,libx264.a都在这里

**Comment by fujiangren** [comment]
十分感谢

**Comment by 27988301** [comment]
java.lang.RuntimeException: connect rtmp server error.这是几个意思啊

**Comment by wlanjie** [comment]
@27988301 rtmpService没连接成功

**Comment by 27988301** [comment]
rtmpService应该是没有问题的，我推送别的rtmp流都是好的。求解释

**Comment by wlanjie** [comment]
把你的链接发来我试下

**Comment by 27988301** [comment]
rtmp://live3.zhihuishu.com/livepkgr/rb_666_1_500
 这个是我推出去的地址。有效的，应该是可以用。

**Comment by wlanjie** [comment]
好的，等晚上我试下

**Comment by 27988301** [comment]
你qq是多少，我们好联系，这是我的279883011
