### ISSUE TITLE
执行脚本build-android.sh的时候出问题

### ISSUE THREAD

**Issue by xieyangxuejun** [wlanjie/AndroidFFmpeg#18]
make-standalone-toolchain.sh used to install a new toolchain into an existing
directory. This is not desirable, as it will not clean up any stale files. If
you wish to remove the install directory before creation, pass --force.

**Comment by wlanjie** [comment]
推流的不用执行脚本，文档还没改，使用ffmpeg的需要，你删除编译目录试一下

**Comment by xieyangxuejun** [comment]
删除文件夹同样报这个错
