### ISSUE TITLE
看项目介绍有用到fdk aac，但好像没看到fdkaac的编译脚本？

### ISSUE THREAD

**Issue by jtyang** [wlanjie/AndroidFFmpeg#19]
rt

**Comment by jtyang** [comment]
sorry，是我没看清，fdk是以源码方式引入的，不过请问下有fdkaac的编译脚本吗，想在ffmpeg内包含这个模块？

**Comment by wlanjie** [comment]
这个没写，如果想在ffmpeg用这个库，编译出来之后，在编译ffmpeg的时候enable这个库就可以了

**Comment by jtyang** [comment]
嗯，看你x264和ffmeg的编译脚本有点像是ijkplayer里的，我也想在ijkplayer加入fdk aac模块，不过对脚本不太熟悉，所以看下你是否写好的脚本。

**Comment by wlanjie** [comment]
是的，我改的ijkplayer里的脚本
